version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
  minio:
    image: minio/minio:latest
    container_name: minio-container
    environment:
      MINIO_ACCESS_KEY: youraccesskey
      MINIO_SECRET_KEY: yoursecretkey
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ../data/minio-data:/data
    command: server --console-address ":9001" /data
  cloud-file-storage:
    container_name: cloud-file-storage
    build:
      context: ..
      dockerfile: docker/Dockerfile-dev
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: cloud-file-storage
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MINIO_HOST: http://minio:9000
      MINIO_ACCESS_KEY: youraccesskey
      MINIO_SECRET_KEY: yoursecretkey
      LOGGING_LEVEL: DEBUG
      MINIO_FILES_BUCKET: user-files
